### ISSUE TITLE
Wrong loop in encode-hash

### ISSUE THREAD

**Issue by Yehouda** [mishoo/cbor.lisp#2]
https://github.com/mishoo/cbor.lisp/blob/5eb332740dfbe95f31e5950da243e73a0d99fa7e/encode.lisp#L186

According to the standard, the "using X" bit has to be after the "of value" bit.
 
https://www.lispworks.com/documentation/HyperSpec/Body/m_loop.htm

Somewhat difficult to read the rule for for-as-hash in the ANSI text, this re-alignment of it:
```
for-as-hash::= var [type-spec] being {each | the}  
               {  
                     {hash-key | hash-keys} {in | of} hash-table   [using (hash-value other-var)]
                                       |  
                   {hash-value | hash-values} {in | of} hash-table        [using (hash-key other-var)]
               } 
```

**Comment by mishoo** [comment]
Indeed, I've been doing it wrong. Somehow, SBCL seems to be forgiving about that. :) Fixed, thank you!
